name: DLG4NLP@2022
tagline: Deep Learning on Graphs for Natural Language Processing
# subtitle: Natural Language Processing
proceedings_title: Deep Learning on Graphs for Natural Language Processing
logo:
    image: static/images/graph4nlp_logo.png
    width: 200px
    height: auto
citation_date: February 2021
analytics: UA-179777566-1
site_url: https://aaai.org/Conferences/AAAI-21/
site_title: DLG4NLP@2022
page_title:
  prefix: 'DLG4NLP@2022'
  separator: ': '
background_image: static/images/background.jpg
organization: DLG4NLP@2022 Team

# Path to the folder of paper images.
paper_images_path: static/images/papers

default_presentation_id: 38931484

# Remove or change to your chat server.
chat_server: aaai-21.rocket.chat
channels_stats_server: https://emnlp2020-channels-stats.azure-api.net

gather_town: https://www.virtualchair.net/events/emnlp2020
connected_papers_conference_name: AAAI2021

calendar:
  start: '2021-02-02 00:00:00-08:00'
  end: '2021-02-09 23:59:59-08:00'
#  start: '2021-2-2'
#    end: '2021-2-9'
